### ISSUE TITLE
DateTime converted to ArrayObject instead of string in custom visitor class

### ISSUE THREAD

**Issue by mvachette** [schmittjoh/serializer#1017]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

I use a custom visitor class (declared using Symfony DIC). 

In the "getResult" method, DateTime objects are converted to ArrayObject, instead of string (I can see that in standard `JsonSerializationVisitor`, DateTime objects are well converted, when printing "$this->getRoot()" in getResults()), that leads to empty string in my final output.

## Steps required to reproduce the problem

1. Configure a custom visitor  class (I'm using JMS serializer with Symfony)
2. launch serialization with data containing some DateTime objects
3. In the "getResult" method, print the content of this->getRoot()

## Expected Result

* DateTime are converted to string at this level (this is what I see if I use standard serializer)

## Actual Result

* DateTime object are converted to ArrayObject at this level
* Even if I declare the standard `JsonSerializationVisitor` class as custom class serializer, the problem occurs: it seems to be related to the  use of a custom serilizer class, not to the class itself

### Configuration of custom serializer
```
custom-serializer:
        class: JMS\Serializer\JsonSerializationVisitor
        arguments: ["@jms_serializer.naming_strategy"]
        tags:
          - { name: jms_serializer.serialization_visitor, format: "custom" }
```
### Serialized data
```php
$data = ['date' => new \DateTime()];
$serializer->serialize($data, 'custom');
```

### Output with "custom" format
Trace in JsonSerializationVisitor:
```php
 public function getResult()
    {
        var_dump($this->getRoot()); exit;
```

Output
```
array (size=1)
  'date'=> 
      object(ArrayObject)[5097]
      private 'storage' =>
        array (size=0)
          empty
</pre>
```

### Output using regular "custom" format
```
array (size=1)
  'date' => string '2018-12-05T11:24:48+01:00' (length=25)
````
