### ISSUE TITLE
SF4: JMS serializer seems to be ignoring global naming strategy

### ISSUE THREAD

**Issue by signmeuptwice** [schmittjoh/serializer#1037]
symfony 4.2
"jms/serializer-bundle": "^3.1",

using dependency injecton in my controller function with `SerializerInterface $serializer`

in my `config > packages > jms_serializer.yaml`  I have the following code but it has not effect whatsoever. Is this normal ? How do we override the default `_` naming strategy to `identical` ?

I am NOT using any other settings anywhere. I literally just installed the bundle and try to configure it.
```yml
`jms_serializer:`
  `visitors:`
    `xml_serialization:`
      `  format_output: '%kernel.debug%'`
  `property_naming:`
 `   id: 'jms_serializer.identical_property_naming_strategy'`
```

**Comment by goetas** [comment]
I tested:

```
composer create-project symfony/skeleton blog
cd blog
composer require jms/serializer-bundle
```

Edit `config/packages/jms_serializer.yaml` with :
```yml
jms_serializer:
    property_naming:
        id: jms_serializer.identical_property_naming_strategy
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
```

and the naming strategy was applied as expected.
