### ISSUE TITLE
add a way to serialize properties not by group

### ISSUE THREAD

**Issue by videni** [schmittjoh/serializer#1043]
```   
Acme\Bundle\PromotionBundle\Entity\Promotion:
    exclusion_policy: ALL
    xml_root_name: promotion
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Promotion]
        name:
            expose: true
            type: string
            xml_attribute: true
            groups: [Promotion]
        startsAt:
            expose: true
            type: DateTime
            xml_attribute: true
            groups: [Promotion]
        endsAt:
            expose: true
            type: DateTime
            xml_attribute: true
            groups: [Promotion]
        rules:
            expose: true
            type: ArrayCollection<Acme\Bundle\PromotionBundle\Entity\PromotionRule>
            groups: [PromotionRule]
        actions:
            expose: true
            type: ArrayCollection<Acme\Bundle\PromotionBundle\Entity\PromotionAction>
            groups: [PromotionAction]
```
I usually configure serialization rule this way .

1.  Give the entity association, such as `rules` property a group name of the entity name itself.  for example,  the `rules`  are group of `PromotionRule`  entities, so its group is 'PromotionRule'.
2.  Give the normal properties group name  as the main entity Name, in this case , it is `Promotion`

then when I serialize Promotion entity, I can decide whether I should serialize associations or not with a meaningful way. but sometime  it is not necessary  to group properties because a group is likely to be used temporary, currently we are forced to add group to every property,  if we didn't it will belong to the `Default` group, it will soon become a nightmare there are so many groups for an entity in the serialization rules. it is very hard to maintain.

I use this library a lot,  I almost have a hundred entities,  I found that serializing entity by grouping property is  not good enough,  I have lot of cases that I only want to serialize a specific properties ,maybe a property tree I specify somewhere, I don't want to give this properties  a group, because it is won't be used  in other case. for example.
```
Acme\Bundle\PromotionBundle\Entity\Promotion:
    exclusion_policy: ALL
    xml_root_name: promotion
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
         rules:
            expose: true
            type: ArrayCollection<Acme\Bundle\PromotionBundle\Entity\PromotionRule>
            properties:
                id:
                    expose: true
                    type: integer
                    xml_attribute: true
                type:
                    expose: true
                    type: string
                    xml_attribute: true
```
I don't mind to write all properties down followed the whole object tree.
