### ISSUE TITLE
SerializationGraphNavigator not receiving correct serializeNull config during initialize

### ISSUE THREAD

**Issue by gabrielspiteri-highlight** [schmittjoh/serializer#1158]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no

If you set the serialize_null yaml config to true with the following configuration:

```yaml
jms_serializer:
   default_context:
        serialization:
            serialize_null: true
```

The context object received by the SerializationGraphNavigator the shouldSerializeNull method always returns false

## Steps required to reproduce the problem

1. Configure JMS to serialize_null: true
2. Serialize and object with null properties

## Expected Result

* Properties with null values show

## Actual Result

* Properties with null values do not show
