### ISSUE TITLE
Switch to change default naming strategy

### ISSUE THREAD

**Issue by MVSAdmin** [schmittjoh/serializer#128]
Hi there!

I can't find a possibility to switch the naming strategy so it's not converting from camelCase to underscored. I really don't understand why this is the default behaviour and setting a SerializedName annotation for all properties in all entities is really nothing we'd like to do.

So, am I missing some switch somewhere?
If not, would it be possible to add that?

Cheers, Anton

**Comment by johnpancoast** [comment]
@schmittjoh or anyone, Is there any update on this? This seems a bit redundant to have to do and could be the default IMO. I can help if needed.
```php
/**
 * @JMS\SerializedName('fooBar')
 */
protected $fooBar;
```

**Comment by goetas** [comment]
Can be solved with a custom naming strategy

**Comment by ianfoulds** [comment]
Having upgraded jms/serilizer-bundle from 1.1 to 2.2 the parameter hack described above did not work. From Symfony 3.4 onward you can override the service definition:

**app/config/services.yaml:**

```
services:
    ....
    jms_serializer.serialized_name_annotation_strategy:
        class: JMS\Serializer\Naming\SerializedNameAnnotationStrategy
        arguments:
            - '@jms_serializer.identical_property_naming_strategy'

```
