### ISSUE TITLE
The serialiser doesn't work since version 3.16.0

### ISSUE THREAD

**Issue by CJDennis** [schmittjoh/serializer#1437]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no

#1366 added the following lines to `src/Metadata/ClassMetadata.php`:
```
            $this->discriminatorGroups,
            $this->xmlDiscriminatorAttribute,
            $this->xmlDiscriminatorCData,
            $this->usingExpression,
            $this->xmlDiscriminatorNamespace,
            $this->xmlRootPrefix,
            $this->isList,
            $this->isMap,
```
I now get `[PHPUnit\Framework\Error\Warning] Undefined array key 16 at vendor\jms\serializer\src\Metadata\ClassMetadata.php:322` when running tests since `$this->discriminatorGroups` (which is already included two lines above) does not exist in the array.

## Steps required to reproduce the problem

1. Use any version from 3.16.0 to 3.18.2
2. Serialise some data

## Expected Result

* The data is serialised.

## Actual Result

* An error `500` in production mode.
* `[PHPUnit\Framework\Error\Warning] Undefined array key 16` in tests.

**Comment by goetas** [comment]
please clear the cache

**Comment by eloirobe** [comment]
I've cleared the cache, both using the command clear:cache and deleting it completely by removing the whole folder, and it still doesn't work. I did some checks and I believe it crashes in JMS\Serializer\Metadata\ClassMetadata.php, method unserializeFromArray. When we check the values inside the param $data, we see the current values:

![image](https://user-images.githubusercontent.com/11217675/198328860-5e7f0aa7-5c1b-41ef-badc-c26862579451.png)

As you can see, the indexes go from 0 to 15, and according to the code there should be more values, so when it reaches $this->discriminatorGroups which is the one that matches index 16 it throws exception.

**Comment by scyzoryck** [comment]
Hi! Are you using [JMSSerializerBundle](https://github.com/schmittjoh/JMSSerializerBundle) ? What is yours cache configuration?

**Comment by eloirobe** [comment]
Yes we're using JMSSerializerBundle
This is the Cache config with memcached also we clear memcached and not work:
```
framework:
    cache:
        default_memcached_provider: "%memcached.parameters%"
        pools:
            doctrine.result_cache_pool:
                adapter: cache.adapter.memcached
            doctrine.system_cache_pool:
                adapter: cache.adapter.memcached
            doctrine.second_level_cache_pool:
                adapter: cache.adapter.memcached
            doctrine.main_cache_region_pool:
                adapter: cache.adapter.memcached

```
