### ISSUE TITLE
Error deserializing an array of objects

### ISSUE THREAD

**Issue by CoderJoeW** [schmittjoh/serializer#1567]
| Q                         | A
| -------------------| -----
| Bug report?         | no
| Feature request? | no
| BC Break report? | no
| RFC?                    | no

## Steps required to reproduce the problem

I have the following JSON as an example

```json
{
	"data": [
		{ "country_id": 0, "country_name": "string" }
	]
}
```

This is the class I created for it

```php
use JMS\Serializer\Annotation\Type as Type;

class AccountCountryList
{
    /**
     * @Type("array<int,AccountCountryListData>")
     */
    public array $data;
}

class AccountCountryListData
{
    public int $countryId;
    public string $countryName;
}
```

## Expected Result

* When I run the following code I am expecting an array of AccountCountryListData inside of AccountCountryList->data

## Actual Result

* Whats actually happening when I run the following code is I get the resulting error
```php
$serializer->deserialize($json, AccountCountryList::class, 'json');
```

I get the following error

```yaml
PHP Fatal error:  Uncaught JMS\Serializer\Exception\RuntimeException: You must define a type for Models\AccountCountryList::$data. in /var/www/phpsdk/vendor/jms/serializer/src/Exception/RuntimeException.php:16
Stack trace:
#0 /var/www/phpsdk/vendor/jms/serializer/src/JsonDeserializationVisitor.php(185): JMS\Serializer\Exception\RuntimeException::noMetadataForProperty()
#1 /var/www/phpsdk/vendor/jms/serializer/src/GraphNavigator/DeserializationGraphNavigator.php(214): JMS\Serializer\JsonDeserializationVisitor->visitProperty()
#2 /var/www/phpsdk/vendor/jms/serializer/src/Serializer.php(256): JMS\Serializer\GraphNavigator\DeserializationGraphNavigator->accept()
#3 /var/www/phpsdk/vendor/jms/serializer/src/Serializer.php(182): JMS\Serializer\Serializer->visit()
#4 /var/www/phpsdk/src/Connect.php(95): JMS\Serializer\Serializer->deserialize()
```
