### ISSUE TITLE
Dynamic expose, aka 'fields' query param

### ISSUE THREAD

**Issue by vlastv** [schmittjoh/serializer#195]
Hi,

Prompt if I understand.

If I need a dynamic inclusion of fields, such as in Facebook "http://api/users?fields=username,picture" I need to create a custom class that implements an interface Exclusion Strategy or are there other ways?

Implemented through the group I do not like, because functional groups I want to leave for other purposes and use chain strategies.

**Comment by korotovsky** [comment]
Hi there!

In our project we successfully implemented dynamic expose with ExclusionStrategyInterface as @damienalexandre said.

But we faced really serious limitation in https://github.com/schmittjoh/serializer.

Imagine, that we have associative array of `Acme\Bundle\HelloBundle\Model\Foo\BazModel` objects. Each object is indexed by its key. For example (`foo`, `bar`).

This is a typical mapping for such situation:

```yml
Acme\Bundle\HelloBundle\Model\Foo\BarModel:
    exclusion_policy: ALL
    virtual_properties:
        getId:
            explose:        true
            type:           integer
            since_version:  1.0

        getHash:
            explose:        true
            type:           array<string, Acme\Bundle\HelloBundle\Model\Foo\BazModel>
            since_version:  1.0
```

So, what we can do with that?

1) `GET /users/1?_fields=id` - query only `id` field.
2) `GET /users/1?_fields=id,hash(id,type)` - query `id` and `hash` with `id` and `type` fields inside `hash` field.

What we can't do?

We completely can't know which key is serialized **at this moment** and that's why we can't do queries like: `GET /users/1?_fields=hash[foo](id,type)`

Problem is here: https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/GenericSerializationVisitor.php#L101

```php
    /**
     * @param array $data
     * @param array $type
     */
    public function visitArray($data, array $type, Context $context)
    {
        // ...
        foreach ($data as $k => $v) {
            $v = $this->navigator->accept($v, $this->getElementType($type), $context);
        // ...
    }
```

**$k** is string - a current serialized key (of this hash, `foo` for example), but this information gets lost when we call `->accept()`.

When each field of `Acme\Bundle\HelloBundle\Model\Foo\BazModel` object is serialized I don't know what value was assigned to **$k** (before) and can't decide whether I should skip class or not https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/Exclusion/ExclusionStrategyInterface.php#L39 

@vlastv @stof @damienalexandre
