### ISSUE TITLE
Support inheritance when looking for a handler in the lazy registry

### ISSUE THREAD

**Issue by vboriesazeau** [schmittjoh/serializer#260]
Hi,

This issue is more a request for an improvement rather than a bug.
It seems the actual code in the `LazyHandlerRegistry` simply checks if there is a handler registered for exactly a given `$typeName`.
But handlers are not found for sub-classes.
Using this configuration in Symfony:

```
myhandler:
        class: %myhandler.class%
        tags:
            -
                name: jms_serializer.handler
                type: AnAbstractClass
                direction: serialization
                format: json
```

the handler is never used if I try to serialize a concrete implementation (sub-class) of `AnAbstractClass`.
That means one must duplicate this handler configuration for each type supported, and change the 'type' key (there is no need to duplicate the handler class itself I guess, It shall be possible to use abstraction in the code). So the working configuration actually shall be:

```
myhandler_for_subclass1:
        class: %myhandler.class%
        tags:
            -
                name: jms_serializer.handler
                type: SubClass1
                direction: serialization
                format: json
myhandler_for_subclass2:
        class: %myhandler.class%
        tags:
            -
                name: jms_serializer.handler
                type: SubClass2
                direction: serialization
                format: json
```

I would suggest the registry in priority gives a handler for exactly the same type name, if any, and after that, as a fallback, goes up in the hierarchy of the type name and looks if there is a dedicated handler, and so on...
Let me know your opinion :).

BR
