### ISSUE TITLE
Exclusion of parent properties failing

### ISSUE THREAD

**Issue by hgraca** [schmittjoh/serializer#282]
Hi,

Im setting up serialization of an entity with yml files, and when I serialize an entity with 2 superclasses, I can not exclude the superclasses properties.
I have a yml file for each entity as such:
top class (abstract):

---

``` yml
Videodock\Bundle\EvpBundle\Entity\BaseContent:
    exclusion_policy: ALL
    read_only: true
    access_type: public_method # defaults to property

    properties:

        id:
            expose: true
```

---

middle class (not abstract):

---

``` yml
Videodock\Bundle\EvpBundle\Entity\Content:
    exclusion_policy: ALL
    read_only: true
    access_type: public_method # defaults to property
```

---

bottom entity class that I want to serialize (not abstract):

---

``` yml
Videodock\Bundle\EvpBundle\Entity\Poll:
    exclusion_policy: ALL
    read_only: true
    access_type: public_method # defaults to property

    properties:

        question:
            expose: true
```

---

When serializing the bottom entity, I want to hide away the properties from the middle class but it shows all properties from all of them regardless.

Is this a bug or am I doing something wrong?

Symfony version: 2.4-dev
jms-serializer-bundle version: 0.13-dev
jms-serializer version: 0.15-dev
