### ISSUE TITLE
make deserialisation of non existing id's configurable

### ISSUE THREAD

**Issue by whitewhidow** [schmittjoh/serializer#333]
Hi,

please look at this:

https://github.com/cdonadeo/serializer/commit/e10c174db982f744cda818736769e41963139e66

this person needs an implementation, where non-existing ids, become new entities

I need a different implementation, wich would ignore non-existing id's, and set the relation to null,

i did this by changing the following:

```
+++ /home/sam/git/badge/vendor/jms/serializer/src/JMS/Serializer/GenericDeserializationVisitor.php
@@ -172,6 +172,10 @@

         $v = $data[$name] !== null ? $this->navigator->accept($data[$name], $metadata->type, $context) : null;

+        if (is_null($this->currentObject)){
+            return;
+        }
+
         if (null === $metadata->setter) {
             $metadata->reflection->setValue($this->currentObject, $v);
```

now my question is, would it not be usefull to be able to configure the serializer via the config, to either, 

try either try to create the non-existing resource, as cdonadeo did, or ignore it, like i did.

instead of the current behaviour, wich causes an exception when trying to deserialize an entity with an id in it, that is not present in the database

Please let me know if there is anything i can do to make this clearer

Thx

EDIT:

after re-reading this, i realize, that my questions regarding beeing able to config this trough the config, belong in the repo for the bundle, but at the same time im assuming it would require changes in both repos for this to be done ? correct?

**Comment by victuxbb** [comment]
Hi! you know something about this?

**Comment by victuxbb** [comment]
ok....I found another solution...
You can define your own DoctrineObjectConstructor creating a service with your class and implementing ObjectConstructorInterface, then you can customize the behaviour.
```yml
services:
    jms_serializer.object_constructor:
        alias: custom.doctrine_object_constructor
        public: false
    custom.doctrine_object_constructor:
        class: Vendor\YourCustomBundle\Serializer\Construction\DoctrineObjectConstructor
        arguments: ['@doctrine','@jms_serializer.unserialize_object_constructor']
```
