### ISSUE TITLE
Static SubscribingHandlerInterface::getSubscribingMethod

### ISSUE THREAD

**Issue by ogizanagi** [schmittjoh/serializer#380]
I wonder if the `getSubscribingMethods` method of the `SubscribingHandlerInterface` needs to be static ?
IMO, this is limiting, as we could not access to the handler instance properties.
Accessing it might be useful in order to configure the supported formats and types from a service container definition.

**e.g**: I've got a basic `Enum` class. This `Enum` class is extended from 3 other classes, doing the same things, but defining different constants. The serializer must do the exact same work for those classes. So in order to do that, I'd like to do such a thing in a Symfony 2 application:

``` yaml
#serializer.yml
services:

    acme_demo.serializer.handler.enum_one:
        class: Acme\DemoBundle\Serializer\Handler\EnumHandler
        arguments: [Acme\DemoBundle\Enum\EnumOne]
        tags:
            - { name: jms_serializer.subscribing_handler }

    acme_demo.serializer.handler.enum_two:
        class: Acme\DemoBundle\Serializer\Handler\EnumHandler
        arguments: [Acme\DemoBundle\Enum\EnumTwo]
        tags:
            - { name: jms_serializer.subscribing_handler }

    acme_demo.serializer.handler.enum_three:
        class: Acme\DemoBundle\Serializer\Handler\EnumHandler
        arguments: [Acme\DemoBundle\Enum\EnumThree]
        tags:
            - { name: jms_serializer.subscribing_handler }
```

The given argument will be the supported type for the handler instance.

I think my example could be solved easily when the #377 will be merged. But there could be other use cases.
