### ISSUE TITLE
Serializing to and deserializing from DateTime is inconsistent

### ISSUE THREAD

**Issue by danwkennedy** [schmittjoh/serializer#394]
The following mapping:

```
Our\Model\Location:
   exclusion_policy: ALL
   properties:
      updatedDateTime:
         type: DateTime<'U'>
```

Deserializes a unix timestamp correctly but serializes a DateTime object to: "2013-04-15T10:54:57+0000". I would expect a Unix timestamp to come out of the serialization process. This keeps us from having a consistent input/output for our APIs
