### ISSUE TITLE
Serializing ArrayCollection of an abstract class returns empty objects

### ISSUE THREAD

**Issue by halloverden** [schmittjoh/serializer#411]
I'm using the [Serlalizer Bundle](https://github.com/schmittjoh/JMSSerializerBundle) with Symfony2, but suspect this is a Serializer issue. 

I have an abstract class "Question":

```
/**
 * App\SurveyBundle\Entity\Question
 * 
 * @ORM\Entity
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="type", type="integer")
 * @ORM\DiscriminatorMap({0 = "App\SurveyBundle\Entity\Question", 3 = "App\SurveyBundle\Entity\MultipleChoice", 2 = "App\SurveyBundle\Entity\SingleChoice", 1 = "App\SurveyBundle\Entity\LikertScale"})
 * @JMS\Discriminator(field="type", map={0: "App\SurveyBundle\Entity\Question", 3: "App\SurveyBundle\Entity\MultipleChoice", 2: "App\SurveyBundle\Entity\SingleChoice", 1: "App\SurveyBundle\Entity\LikertScale"})
 * @ORM\HasLifeCycleCallbacks
 */
abstract class Question {
    /**
     * Question type
     */
    public function getQuestionType() {
        if ($this instanceof MultipleChoice) {
            return 3;
        } else if($this instanceof SingleChoice) {
            return 2;
        } else if($this instanceof LikertScale) {
            return 1;
        } else {
            return 0;
        }
    } 
}
```

...extended by three sub classes, using this yml annotation file (Example for the "SingleChoice" extended class).

```
App\SurveyBundle\Entity\SingleChoice:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: integer
            groups: [default]
        questionText:
            expose: true
            serialized_name: questionText
            type: string
            groups: [default]
        created:
            expose: true
            type: DateTime
            groups: [default]
        survey:
            expose: true
            type: App\SurveyBundle\Entity\Survey
            groups: [deserialization]
    virtual_properties:
        getQuestionType:
            serialized_name: type
            type: integer
            groups: [default]
```

The abstract class "Question" is used by my "Survey" class, which holds an ArrayCollection of Questions.

```
App\SurveyBundle\Entity\Survey:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: integer
            groups: [default]
        created:
            expose: true
            type: DateTime
            groups: [default]
        name:
            expose: true
            type: string
            groups: [default]
        questions:
            expose: true
            type: ArrayCollection<App\SurveyBundle\Entity\Question>
            groups: [default]
```

When serializing a survey

```
$serializer->serialize($survey, 'json', SerializationContext::create()->enableMaxDepthChecks()->setGroups(array('default'));
```

...this is the output 

```

{
    id: 1,
    created: "2015-03-02T10:48:53+0100",
    name: "test",
    questions: [
        { },
        { },
        { },
        { },
        { },
        { },
        { }
    ]
}
```

Are anyone else seeing this kind of behavior? Am I doing something wrong?
