### ISSUE TITLE
Groups is ignored

### ISSUE THREAD

**Issue by digitalkaoz** [schmittjoh/serializer#440]
Hey,

it seems im misusing groups :/

```yaml
My\Entity:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        id:
            expose: true
        bar:
            expose: true
        foo:
            groups: [import]
```

if i serialize a `\My\Entity` with

```php
$serializer->serialize($object, 'json');
``` 

the `foo` attribute is still in the serialized fields. (If i remove it from the mapping, it doesnt get serialized)

even if i explicitly pass a group it wont work:
```php
$context = SerializationContext::create()->enableMaxDepthChecks();
$context->setGroups(['Default']);

$serializer->serialize($object, 'json', $context);
``` 

i excpect the `foo` attribute only to be serialized if i pass in the `import`group!

so whats wrong here? maybe the yaml format or attribute name changed?
