### ISSUE TITLE
Multiple schemas for the same class

### ISSUE THREAD

**Issue by estahn** [schmittjoh/serializer#471]
Hi Guys,

I would like to be able to create different schemas for the same class. I was thinking on using different YML files to achieve this. I couldn't find a way to directly load a YAML file though.

Example:

```
class Foo { protected $id; }

YAML1:
FooBar:
    exclusion_policy: ALL
    accessor_order: alphabetical
    properties:
        id: ~

YAML2:
FooBar:
    exclusion_policy: ALL
    accessor_order: alphabetical
    properties:
        id:
            serialized_name: fubar

```

Is this only possible by storing the YML files in different directories and then load them via `addMetadataDir`? Other ideas?

Enrico
