### ISSUE TITLE
max_depth in YML config is ignored

### ISSUE THREAD

**Issue by jakenoble** [schmittjoh/serializer#498]
The following is not being read as expected because only ID is shown. But the `max_depth` value is being ignored. I have cleared the cache several times now but still no luck.

Have I missed something when using `max_depth` and YML?

```
AppBundle\Entity\School:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
    programs:
      expose: true
      max_depth: 1
```
