### ISSUE TITLE
XML deserialization properties null when using default namespace

### ISSUE THREAD

**Issue by shabbyrobe** [schmittjoh/serializer#504]
When I deserialize an XML document that uses a default namespace, none of the properties get set. I've tracked the problem down to https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/XmlDeserializationVisitor.php#L259 but I'm not entirely sure if it's me doing something wrong or not.

If it isn't my script, I'm happy to work up a fix if you'd like.

PHP version is 5.6.

`bug.php`:

``` php
<?php
namespace Pants
{
    class Test
    {
        private $name;

        public function getName()   { return $this->name; }
        public function setName($v) { $this->name = $v; }
    }
}

namespace
{
    require __DIR__.'/vendor/autoload.php';

    $serializer = JMS\Serializer\SerializerBuilder::create()
        ->addMetadataDir(__DIR__.'/resources', 'Pants')
        ->build();

    // works when using prefixes
    $xml = '
        <t:test xmlns:t="urn:pants.xsd">
            <t:name>HELLO</t:name>
        </t:test>
    ';
    var_dump($serializer->deserialize($xml, 'Pants\Test', 'xml'));

    // doesn't work when not using prefixes
    $xml = '
        <test xmlns="urn:pants.xsd">
            <name>HELLO</name>
        </test>
    ';
    var_dump($serializer->deserialize($xml, 'Pants\Test', 'xml'));
}
```

`resources/Pants.yml`:

``` yaml
Pants\Test:
    xml_root_name: Test
    xml_root_namespace: urn:pants.xsd

    properties:
        name:
            expose: true
            access_type: public_method
            serialized_name: name
            xml_element:
                namespace: 'urn:pants.xsd'
            accessor:
                getter: getName
                setter: setName
            type: string
```

Output:

```
class Pants\Test#58 (1) {
  private $name =>
  string(5) "HELLO"
}
class Pants\Test#58 (1) {
  private $name =>
  NULL
}
```
