### ISSUE TITLE
Possible to set xsi:schemalocation?

### ISSUE THREAD

**Issue by netsensei** [schmittjoh/serializer#505]
While serializing a set of PHP objects into XML: I'm failing to set the `xsi:schemalocation` attribute on the root element.  

I'm using YML annotations for the root level element.

I've tried configuring it like this:

````yaml
myRootElement:
    xml_namespaces:
        "example": "http://www.example-schema.org"
        "xsi": "http://www.w3.org/2001/XMLSchema-instance"
        "xsi:location": "http//example.com/schema.xsd"
```

This will throw an error `DOMException: Namespace Error` in `XmlSerializationVisitor.php` on line 203. The `addNamespaceAttributes` internally always prefixes `xmlns` to the prefix, so you end up with something like: `xmlns:xsi:location`. The `setAttributeNS` call is not accepting that as a qualified attribute name.

Is there a way to work around this?

**Comment by netsensei** [comment]
Okay, looks like #433 provides a workaround:

The idea is that I add an extra property to my root class and add an `XmlAttributeMap` property which defines the `xsi:location` namespace instead of using `xml_namespaces`:

Something along these lines:

YAML:
```yaml
myRootElement:
    xml_namespaces:
        "lido": "http://www.lido-schema.org"
        "xsi": "http://www.w3.org/2001/XMLSchema-instance"
   properties:
       xsiLocation
          xml_attribute_map: true
```

PHP
```php
class myRootElement {
   private $xsiLocation;

   public function __construct()
   {
      $this->xsiLocation = ["xsi:location" => "http//example.com/schema.xsd"];
   }
}

This feels a it counterintuitive: are there better solutions / alternatives where I can avoid hard coding the xsd location in a class?
