### ISSUE TITLE
Possible to prefix the root element while serializing?

### ISSUE THREAD

**Issue by netsensei** [schmittjoh/serializer#506]
While serializing an object to XML: is it possible to add a namespace prefix to the root element of the XML?

I'm using YML annotations to de/serialize my XML like this:

``` yaml
myXmlElement:
    xml_root_name: "example:foobar"
    xml_root_namespace: "http://www.example.ns"
```

This will yield:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<example:foobar xmlns:example="http://www.example.ns">
</example>
```

The output is correct. I was just wondering if including the prefix in `xml_root_name`, is intentionally designed like that. I'd expected a separate property `xml_root_prefix` (or similar) that allows me to set the prefix explicitly.

Even weirder: child elements will automatically inherit the prefix set in `xml_root_name`.
