### ISSUE TITLE
Attributes in simpleContent element to property and vice versa

### ISSUE THREAD

**Issue by crazycodr** [schmittjoh/serializer#536]
I have the following XML:

```xml
<content>
	<subject topic-id="123">This is the topic name</subject>
</content>
```

Which is made possible using the following XSD construct:

```xml
<xs:complexType name="subject-type">
	<xs:simpleContent>
		<xs:extension base="non-empty-string">
			<xs:attribute name="topic-id" type="xs:positiveInteger" use="required"/>
		</xs:extension>
	</xs:simpleContent>
</xs:complexType>
```

How can i extract the attribute "topic-id" to a property of the Content class and also retrieve the simple-content and put it into another property? My first guess was to use this:

```yml
subject:
	type: string
subjectID:
	type: integer
	xml_attribute: true
	serialized_name: subject/topic-id
```

But it doesn't work. Whats the good approach?

Thanks
