### ISSUE TITLE
the serializer doesn't work as expected when only the setter  and getter method exists

### ISSUE THREAD

**Issue by videni** [schmittjoh/serializer#545]
I have two  class   as you can see below.

```
PaymentMethod  extends AbstractTranslatable{

 /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return $this->translate()->getName();
    }
    /**
     * {@inheritdoc}
     */
    public function setName($name)
    {
        $this->translate()->setName($name);
        return $this;
    }

}

```

```
class AbstractTranslatable {
    protected $translations;
 /**
     * {@inheritdoc}
     */
    public function getTranslations()
    {
        return $this->translations;
    }
}

```

the serialization metadata for class PaymentMethod 

```
Acme\Component\Payment\Model\PaymentMethod:
    exclusion_policy: ALL
    xml_root_name: payment-method
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
        code:
            expose: true
            type: string
        name:
            expose: true
            type: string
        createdAt:
            expose: true
            type: DateTime
        updatedAt:
            expose: true
            type: DateTime
```

when I try to serialize class PaymentMethod, there is no `name` key in the  serialized json data I got, but the `translations` property of its parent returned,  this  is not expected result, any body know why?
