### ISSUE TITLE
Form validation error response - field names not converted from camel case to underscore

### ISSUE THREAD

**Issue by lopsided** [schmittjoh/serializer#587]
When I return my form errors like:

```
return View::create($form, 400);
```

The errors are returned like:

```
{"code":400,"message":"Validation Failed","errors":{"children":{"firstName":{"errors":["Your first name
 must not be empty."]},"lastName":{},"email":{}}}}
```

Where I was expecting `firstName` and `lastName` to come through as `first_name` and `last_name`.

All the rest of the serialization works fine (ie, returning objects, converting form posts etc). Just this. 

My config (I'm using the FOSRestBundle):

```
fos_rest:
    param_fetcher_listener: force
    body_listener:
        array_normalizer: fos_rest.normalizer.camel_keys
    view:
        default_engine: json
        view_response_listener: force
        templating_formats:
            html: true
            twig: false
    routing_loader:
        default_format: json
    format_listener:
        rules:
            - { path: '^/', priorities: [ 'json' ], fallback_format: json, prefer_extension: false }
    serializer:
        serialize_null: true

jms_serializer:
    metadata:
        cache: ~
        directories:
            core:
                namespace_prefix: "MyProject\\Core"
                path: "@MyProjectApiBundle/Resources/config/serializer"
```

Apologies if this is a configuration problem.

I posted this here as the file that seems to be creating the response is `JMS/Serializer/Handler/FormErrorHandler.php` and I can't see if/where it is applying any naming strategy to the field names. (ie, line 145; `$children[$child->getName()]`)
