### ISSUE TITLE
[Idea] Inline name

### ISSUE THREAD

**Issue by altitude** [schmittjoh/serializer#629]
Currently, the `inline` attribute in your mapping lets you expose nested properties directly:

```JSON
{"cart": {"value": 13.04}}
```

with `inline: true` becomes

```JSON
{"value": 13.04}
```

It would be great to be able to define custom names for the inlined object properties. 

```YAML
cart:
    expose: true
    inline: true
    inline_names:
        value: cart_value
```

```JSON
{"cart_value": 13.04}
```

One reason I'm proposing this is because I often have conflicts between inlined and parent object properties names, like `id` and end up with an extra method & virtual property.

**Comment by altitude** [comment]
Indeed, adding a `serialized_name` to the cart mapping would do the trick

```YAML
value:
    expose: true
    serialized_name: cart_value
```

```JSON
{"cart_value": 13.04}
```

But it also means that `value` will be serialized to `cart_value` everywhere.

Another way to put it would be to have nested mapping:

```YAML
cart:
    expose: true
    inline: true
    properties:
        value:
            serialized_name: cart_value
```

It is also possible that there's already way to achieve this, or that nobody actually needs to do it. 

Either way, thanks for your help :-)
