### ISSUE TITLE
serializer doesn't serialize traits

### ISSUE THREAD

**Issue by exchentrix** [schmittjoh/serializer#638]
Hey,

thanks for this awesome bundle. 

I've noticed that serializer doesnt serialize traits. I've this is my entity:

```php
<?php

namespace BusinessBundle\Entity\Acl;

use Symfony\Component\Validator\Constraints as Assert,
    Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

use FOS\UserBundle\Model\User as BaseUser;

use Doctrine\ORM\Mapping as ORM;

use Gedmo\Timestampable\Traits\TimestampableEntity;

use JMS\Serializer\Annotation as Serialize;

/**
 * @Serialize\ExclusionPolicy("all")
 */
class User extends BaseUser
{
    /**
     * Hook timestampable behavior
     */
    use TimestampableEntity;

    /**
     * @var \DateTime $createdAt
     *
     * @Serialize\Expose
     * @Serialize\Type("DateTime")
     * @Serialize\Since("0.15.0")
     * @Serialize\Groups({"acl"})
     */
    protected $createdAt;

    ....
}
```

When serializing this, I get 

```yaml
{
	"user":{
		"email": "christian@foo.de",
		"last_login": "2016-09-07T14:04:10+0200",
		"name": "Christian",
		"created_at": null, // it's null :(
		"newsletter": true,
		"ip_address": "192.168.56.1",
		"locale": "de",
		"country": "DE"
	}
}
```

In the database the value of `created_at` field is `2016-09-06 21:21:43`. Is there anything I'm doing wrong or is it just not possible?

Best
Christian
