### ISSUE TITLE
PropertyMetadata exposes non-configured fields with doctrine inheritance

### ISSUE THREAD

**Issue by scaytrase** [schmittjoh/serializer#639]
PropertyMetadata silently ignores class-wide `access_type: public_property` and `exclusion_policy: NONE`

Given a Doctrine entity with a mapped private (stored in DB but no accessors) field:

```php
class MyEntity
{
    /** @var  int|null */
    private $id;
    /** @var  string */
    private $privateField;

    public function __construct($privateField)
    {
        $this->privateField = $privateField;
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    public function doSomeBusinessLogic()
    {
        return sha1($this->privateField);
    }
}

```

with mapping
```yaml
Entity\MyEntity:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    privateField: {type: string}
```

and serializer configuration
```yaml
Entity\MyEntity:
  exclusion_policy: NONE
  access_type: public_method
```

Property is created here

https://github.com/schmittjoh/serializer/blob/fe13a1f993ea3456e195b7820692f2eb2b6bbb48/src/JMS/Serializer/Metadata/Driver/YamlDriver.php#L72

But this exception

https://github.com/schmittjoh/serializer/blob/fe13a1f993ea3456e195b7820692f2eb2b6bbb48/src/JMS/Serializer/Metadata/PropertyMetadata.php#L66

is not thrown because the property is not described here:

https://github.com/schmittjoh/serializer/blob/fe13a1f993ea3456e195b7820692f2eb2b6bbb48/src/JMS/Serializer/Metadata/Driver/YamlDriver.php#L80

So the `PropertyMetadata` is created with `getter=null` and `setter=null` which makes it behave like `access_type: property` here

https://github.com/schmittjoh/serializer/blob/fe13a1f993ea3456e195b7820692f2eb2b6bbb48/src/JMS/Serializer/Metadata/PropertyMetadata.php#L86

This makes the serialization of the private field.

-----

My personal proposal is 
* mark property as `Excluded` automatically if the class-wide (or property-wide if configured) `access_type` is `public_method` and no `getter` configured.
* mark property as `ReadOnly` automatically if the class-wide (or property-wide if configured) `access_type` is `public_method` and no `setter` configured.
