### ISSUE TITLE
YML virtual_properties no group exlcusion

### ISSUE THREAD

**Issue by ranqx-api** [schmittjoh/serializer#656]
Group property defined under virtual_properties don't seem to exclude the virtual properties when the group isn't supplied.

## YML
```yml
My\Bundle\Entity\Finance:
    exclusion_policy: ALL
    access_type: public_method
    xml_root_name: finance
    properties:
        id:
            groups: [finance, min]
            access_type: property
        currency:
            groups: [finance]
        period:
            groups: [finance]
            serialized_name: year_ending
        staffNumber:
            groups: [finance]
    virtual_properties:
        getRawDataParsed:
            groups: [finance_account]
            serialized_name: finance_accounts
```

## Supplied context
```php
$context->addGroups(['finance', BaseController::CONTEXT_GROUP_MIN]);
```

In the YML, the parent group is "finance", and the virtual property group is "finance_account".  (`CONTEXT_GROUP_MIN` is an always-on "min" group to display IDs only)

## Expected behavior
The exclusion of the virtual property data, unless both "finance" and "finance_account" groups are supplied to the context.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<result xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <entry>
        <id>186</id>
        <currency>
            <![CDATA[NZD]]>
        </currency>
        <staff_number>3</staff_number>
        <year_ending>
            <![CDATA[2016-03-01T00:00:00+13:00]]>
        </year_ending>
    </entry>
</result>
```

## Actual
Virtual property is output
```xml
<?xml version="1.0" encoding="UTF-8"?>
<result xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <entry>
        <id>186</id>
        <currency>
            <![CDATA[NZD]]>
        </currency>
        <staff_number>3</staff_number>
        <finance_accounts>
            <entry>
                <id xsi:nil="true"/>
                <code>
                    <![CDATA[ASS]]>
                </code>
                <title>
                    <![CDATA[Bank #1]]>
                </title>
                <price>56000</price>
                <type>
                    <![CDATA[A-CB]]>
                </type>
                <original_type>
                    <![CDATA[A-CB]]>
                </original_type>
            </entry>
            <entry>
                <id xsi:nil="true"/>
                <code>
                    <![CDATA[ASS]]>
                </code>
                <title>
                    <![CDATA[Bank #2]]>
                </title>
                <price>-13000</price>
                <type>
                    <![CDATA[L-CB]]>
                </type>
                <original_type>
                    <![CDATA[L-CB]]>
                </original_type>
            </entry>
        </finance_accounts>
        <year_ending>
            <![CDATA[2016-03-01T00:00:00+13:00]]>
        </year_ending>
    </entry>
</result>
```
