### ISSUE TITLE
How to handle DateTime srialization with fromArray method ?

### ISSUE THREAD

**Issue by VincentClair** [schmittjoh/serializer#723]
Hello,

Here is what i intended to make in a simplify example:
```
$data = ['startDateTime' => new DateTime()];
$object = $serializer->fromArray($data, $type);
```
$serializer come from the service available in JMSSerializerBundle.
I get the following error from DateHandler, line 166:
"Catchable Fatal Error: Object of class DateTime could not be converted to string".

My expectation was to call "fromArray" method on some already defined (native) sub objects.

Could you help me to find the good practice ?

**Comment by goetas** [comment]
From array is ment to convert:

```php
$data = ['startDateTime' => "2016-01-08 20:30:40"];
$object = $serializer->fromArray($data, $type);
```
if you have native sub objects, you can use a "Native" virtual type, and a custom deserializer on it that returns the value itself

**Comment by VincentClair** [comment]
I will get an eye to make a "Native" virtual type.

As i only use deserialization to create an object or populate an existing one, maybe there is a better way ?


Another possibility would be to add the following code to `DateHandler::parseDateTime()`:
```php
        if ($data instanceof \DateTimeImmutable || $data instanceof \DateTime) {
            return $data;
        }
```
Will it be bad?


For the little story, to go further, my aim is to make a service that take an array (build by graphql mutation), create an object (optionally populate an existing object), validate it using Symfony Validator service and return it if it is a success. The service must replace all regular Symfony forms.

Here some more code:

GraphQL mutation:
```
Mutation:
    type: object
    config:
        description: "App Bundle"
        fields:
            createEntity:
                type: "Entity!"
                args:
                    input:
                        type: createEntityInput!
                resolve: |
                    @=service('entity_manager').save(
                        service('graphql_validator').validate(args['input'], "AppBundle\\Model\\Entity")
                    )

createEntityInput:
    type: input-object
    config:
        fields:
            title:
                type: "String"
                description: "Title."
            startDateTime:
                type: "DateTime"
                description: "Start datetime."
```

GraphQL already convert and validate DateTime input fields (with custom scalar types https://github.com/overblog/GraphQLPhpGenerator/blob/24f912652181e7d114aa5526865502848990573e/tests/DateTimeType.php).

I have set serialization too:
```
AppBundle\Model\Entity:
    properties:
        startDateTime:
            type: DateTime<'Y-m-d H:i:s'>
            serialized_name: startDateTime
            access_type: public_method
```

**Comment by goetas** [comment]
you can so something as:

```yml
AppBundle\Model\Entity:
    properties:
        startDateTime:
            type: Native
            serialized_name: startDateTime
            access_type: public_method
```

and having a handler as: 

```php
class MyHandler implements SubscribingHandlerInterface
{
    public static function getSubscribingMethods()
    {
        return array(
            array(
                'direction' => GraphNavigator::DIRECTION_DESERIALIZATION,
                'format' => 'json',
                'type' => 'Native',
                'method' => 'deserialize',
            ),
        );
    }

    public function deserialize(JsonDeserializationVisitor $visitor, $object, array $type, Context $context)
    {
        return $object;
    }
}
```
```

**Comment by VincentClair** [comment]
to help others, the service as yaml config:

```
    native_handler:
        class: AppBundle\Serializer\NativeHandler
        tags:
            -
                name: jms_serializer.subscribing_handler
                type: Native
                format: json
```
