### ISSUE TITLE
Discriminator field named false treated as a boolean

### ISSUE THREAD

**Issue by rcwsr** [schmittjoh/serializer#791]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

## Steps required to reproduce the problem

Map discriminator field named `false`:

```
discriminator:
    field_name: type
    map:
        false: FalseExpression
```

## Expected Result

```
"requirement": {
  "type": "false"
},
```

## Actual Result

```
"requirement": {
  "type": 0
},
```

**Comment by goetas** [comment]
This is an intrinsic problem of the YAML format. 

If you define your yaml as: 

```yml
discriminator:
    field_name: type
    map:
        'false': FalseExpression
```

you will get:

```json
"requirement": {
  "type": "false"
},
```
