### ISSUE TITLE
@MaxDepth jms/serializer-bundle 2.2

### ISSUE THREAD

**Issue by brunorafaeI** [schmittjoh/serializer#842]
max_depth in the yml or in the annotation don't work for me (version 2.2).
```
#AppBundle\Resources\config\serializer\Entity.Place.yml
AppBundle\Entity\Place:
    exclusion_policy: none
    properties:
        place_id:
            groups: ['place', 'price']
        place_name:
            groups: ['place', 'price']
        place_address:
            groups: ['place', 'price']
        prices:
            groups: ['place']
            max_depth: 2
```

I have this like issue:
```
[
    {
        "place_id": 1,
        "place_name": "Tour Eiffel",
        "place_address": "5 Avenue Anatole France, 75007 Paris",
        "prices": [
            {
                "price_id": 2,
                "price_type": "less_than_12",
                "price_value": 5.99
            },
            {
                "price_id": 3,
                "price_type": "for_all",
                "price_value": 7.5
            },
            {
                "price_id": 4,
                "price_type": "people",
                "price_value": 2.75
            }
        ]
    },
    {
        "place_id": 2,
        "place_name": "Mont-Saint-Michel",
        "place_address": "50170 Le Mont-Saint-Michel",
        "prices": []
    }
]
```

when I change max_depth per 1, the date information disappears, everything then appears is {},{},{}
we have an idea, why it doesn't work?
