### ISSUE TITLE
Not all virtual properties are serialized

### ISSUE THREAD

**Issue by DjangoFR** [schmittjoh/serializer#864]
I'm currently trying to get serializer to work with FOSElasticaBundle and it is unfortunately not possible for me to create several virtual properties at the same time. 

Used versions:
jms/metadata                  1.6.0 
jms/parser-lib                  1.0.0  
jms/serializer                   1.10.0 
jms/serializer-bundle       2.3.1

```yaml
    virtual_properties:
        getName:
            serialized_name: name_it
            type: string
        expression_prop:
            exp: object.getName()
            serialized_name: name_en
            type: string
        expression_prop:
            exp: object.getName()
            serialized_name: name_de
            type: string
        expression_prop:
            exp: object.getName()
            serialized_name: name_fr
            type: string
```

Later different analyzers are applied in elasticsearch...

```json
},
"name_it": {
"analyzer": "custom_analyzer_it",
"type": "text"
},
"name_en": {
"analyzer": "custom_analyzer_en",
"type": "text"
}
...
```

## Expected Result
```json
{
  "id": 1,
  "name": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr",
  "name_it": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr",
  "name_en": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr",
  "name_de": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr",
  "name_fr": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr"
}
```

## Actual Result

```json
{
  "id": 1,
  "name": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr",
  "name_en": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr"
}
```
