### ISSUE TITLE
Configuration schema validation

### ISSUE THREAD

**Issue by smilesrg** [schmittjoh/serializer#881]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

I think that XML and YML configs schema validation must be implemented, it could save many hours for developer. For example, this YML config has valid markup but incorrect schema:
```yaml
Vendor\Namespace\Class:
  exclusion_policy: ALL
  access_type: public_method
  properties:
    someProperty:
      access_type: public_method
        accessor:
          getter: getSomeOtherProperty
          setter: setSomeOtherProperty
```
No warnings or exceptions are thrown.

This schema schould be slightly different at someProperty/accessor element:
```yaml
    someProperty:
      access_type: public_method
      accessor:
        getter: getSomeOtherProperty
        setter: setSomeOtherProperty
```

But developer may not notice this error, that's why schema validation should be implemented.
