### ISSUE TITLE
Recursion detected error when serialization groups are in use

### ISSUE THREAD

**Issue by TomiS** [schmittjoh/serializer#96]
I have a following quite complex array with parent objects and child objects, let's say `User` and `Avatar`. Both are, however, very simple objects (not Doctrine Entities or anything)

```
- user1
    - avatar1
    - avatar2
- user2
    - avatar1
    - ...
    - avatarN
- ...
```

When I serialize this multi-dimensional array normally without using groups everything works just fine.

BUT: Let's say I try to limit the serialized output of every `User` object by creating a serialization group because I don't want all the fields of the User exposed. Everything works ok until I include the field `avatars` (array of Avatar instances) in the exposed fields group. If I do that I'm greeted with this error: `Warning: json_encode() [<a href='function.json-encode'>function.json-encode</a>]: recursion detected in .../vendor/jms/serializer/src/JMS/Serializer/JsonSerializationVisitor.php line 29`

The funny thing really is, it works great for the whole array. Problems only occur when I try to limit the output using groups feature.

My User object's serialization config looks like this:

```
My\FoobarBundle\Model\User:
    exclusion_policy: none
    properties:
        name:
            groups: [query]
        avatars:
            groups: [query]
```

Or is this just some missing configuration I'm not familiar to?
